config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "home#index"

  resources :feeds, only: [:index]

  resources :organizations, only: [] do
    resource :feed, only: [:show]
    resources :boards, only: [:index]
  end

  resources :boards, only: [] do
    resource :feed, only: [:show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:trello]

  validates :name, :trello_token, :trello_secret, presence: true

  before_save :ensure_authentication_token

  def ensure_authentication_token
    return if authentication_token.presence
    self.authentication_token = generate_authentication_token
  end

  def self.from_trello_oauth auth_data
    User.where(provider: 'trello', uid: auth_data.uid).first_or_create do |user|
      user.email = auth_data.info.email
      user.name = auth_data.info.name
      user.password = Devise.friendly_token
      user.password_confirmation = user.password
      user.trello_token = auth_data.extra.access_token.token
      user.trello_secret = auth_data.extra.access_token.secret
    end
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :define_layout

  protected

  def trello_client
    return unless user_signed_in?
    @trello_client ||= Trello::Client.new(
      consumer_key: ENV['TRELLO_KEY'],
      consumer_secret: ENV['TRELLO_SECRET'],
      oauth_token: current_user.trello_token,
      oauth_token_secret: current_user.trello_secret
    )
  end

  def current_trello_user
    return unless user_signed_in?
    @current_trello_user ||= trello_client.find(:member, current_user.uid)
  end

  def define_layout
    request.xhr? ? false : 'application'
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @organization = trello_client.find(:organizations, params[:organization_id])
    @boards = @organization.boards
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # before_action :authenticate_user_with_token!
  before_action :authenticate_user!

  def index
    @organizations = current_trello_user.organizations.sort_by(&:display_name)
  end

  def show
    calendar = TrelloCalendar[calendar_type].new(trello_client, calendar_id)
    render text: calendar.to_ics, mime_type: Mime::Type.new("text/calendar")
  end

  private

  def calendar_type
    @calendar_type ||= [:organization, :board].find do |type|
      params.key?(:"#{ type }_id")
    end
  end

  def calendar_id
    params[:"#{ calendar_type }_id"]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to feeds_path if user_signed_in?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def trello
    @user = User.from_trello_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:success, :success, kind: "Trello") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Lets you yield vars containing the result of the given expressions
  #
  # @example Bind and load user's specific data
  #   let current_user.email, current_user.role.name do |email, role|
  #     # Use the local vars here
  #   end
  #
  def let *args
    yield *args
  end

  # Get an ActiveRecord::Base instance and and produce a list of
  # all the error messages present in instance.errors.messages pepended
  # by the message passed as the second argument
  def error_messages_html instance, message = ""
    buffer = message
    buffer << '<ul>'
    buffer << instance.errors.messages.to_a.reduce("") do |buff, err|
      field = "#{t("activerecord.attributes.#{instance.class.to_s.underscore}.#{err.shift}")}"
      err.shift.each do |msg|
        buff << "<li>#{ the_item(field) } #{ msg }</li>"
      end
      buff
    end
    buffer << '</ul>'
    buffer.html_safe
  end


  def the_item str
    t((%w(a e i o u y).include?(str[0]) ? :the_short_item : :the_item), item: str)
  end

  # Appends the given params to the current url while keeping existing params
  #
  # @param [Hash] params The params hash we want to build into query string
  #
  # @return [String] The new query string
  #
  def current_page_plus_params params
    path = request.fullpath

    if path.match(/\?/)
      path, query = path.split(/\?/)
      existing = Hash[query.split('&').map { |a| a.split( /=/ ) }]
      params = existing.merge(params.stringify_keys)
    end

    [path, params].join("?")
  end

  # Converts flash types to :success or :error to conform to what
  # twitter bootstrap can handle
  #
  def homogenize_flash_type type
    case type.to_sym
    when :notice then :success
    when :alert then :warning
    when :error then :danger
    else type
    end
  end

  def icon_class_for type
    case type
    when :success then "fa-check"
    when :error then "fa-warning"
    else "fa-exclamation-triangle"
    end
  end

  def display_flash
    # Get devise errors if present
    if respond_to?(:devise_error_messages!)
      flash[:alert] = devise_error_messages! if defined?(resource) && devise_error_messages! != ""
    end

    # Render empty string if no flash
    return "" if flash.empty?

    # Make a div.alert for each message and join the whole
    messages = flash.map do |type, message|
      flash.delete(type)
      content_tag :div, class: "alert alert-#{ homogenize_flash_type(type) } alert-dismissable" do
        buffer  = content_tag(:button, type: "button", class: "close", "data-dismiss" => "alert") do
          content_tag(:span, '&times;'.html_safe)
        end
        buffer +=  content_tag(:i, "", class: "fa #{ icon_class_for(type) } pull-left")
        buffer += content_tag(:p, message.html_safe)
      end
    end

    # Join the messages and make sure markup is correctly displayed
    messages.join.html_safe
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/boards/index.html.haml
- @boards.each do |board|
  %li.list-group-item
    = board.name

    .input-group.feed-url-input-group
      %span.input-group-addon
        %button.copy-feed-url-btn{ :"data-clipboard-target" => "feed-url-board-#{ board.id }", title: "Click me to copy the feed URL to your clipboard."}
          = fa_icon 'copy'

      %input.feed-url.form-control{ id: "feed-url-board-#{ board.id }", disabled: 'disabled', value: board_feed_path(board_id: board.id, format: 'ics', only_path: false, auth_token: current_user.authentication_token) }

app/views/feeds/index.html.haml
%h1 Flux ICS

- @organizations.each do |organization|
  .organization-feed-panel.panel.panel-default
    .panel-heading
      %h3.panel-title= organization.display_name
    .panel-body
      %p
        Flux ICS pour l'organisation
        %strong= organization.display_name
        \:


        .input-group.feed-url-input-group
          %span.input-group-addon
            %button.copy-feed-url-btn{ :"data-clipboard-target" => "feed-url-organization-#{ organization.id }", title: "Click me to copy the feed URL to your clipboard."}
              = fa_icon 'copy'

          %input.feed-url.form-control{ id: "feed-url-organization-#{ organization.id }", disabled: 'disabled', value: organization_feed_path(organization_id: organization.id, format: 'ics', only_path: false, auth_token: current_user.authentication_token) }

      %hr

      = link_to "#organization-boards-#{ organization.id }", class: 'btn btn-block btn-default collapsed organization-boards-collapse-btn', data: { toggle: 'collapse', :"details-url" => organization_boards_path(organization_id: organization.id) } do
        Afficher les Boards
        %span.caret


    %ul.organization-boards.list-group.collapse{ id: "organization-boards-#{ organization.id }" }
      %li.list-group-item.loader
        = fa_icon 'spinner spin'
        Loading ...

app/views/home/index.html.haml
= link_to user_omniauth_authorize_path(:trello), class: 'btn btn-primary btn-lg trello-sign-in-home-button' do
  = image_tag("trello-logo.png", size: '16x16')
  Sign in with Trello

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Trello Calendar Feed
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header#top.navbar.navbar-default.navbar-fixed-top{role: "banner"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Trello Calendar Feed", root_path, class: "navbar-brand"
        %nav.collapse.navbar-collapse.bs-navbar-collapse{role: "navigation"}
          %ul.nav.navbar-right.navbar-nav
            - if user_signed_in?
              %li
                %a
                  Signed in as :
                  \#{current_user.name}
              %li
                = link_to destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" do
                  Sign out
            - else
              %li
                = link_to "Sign in with Trello", user_omniauth_authorize_path(:trello)
    = display_flash
    .container.main-container
      = yield

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>